@startuml
title Переказ коштів (зі сторони відправника)

autonumber

actor Користувач as user
participant Застосунок as app
participant "Сервер банку" as BS
participant "База даних" as DB
participant "Банк-отримувач" as RB

user -> app : Обрати дію <<переказ коштів>>
activate app

LOOP Поки коштів не достатньо або поки переказ скасовано

  user <-- app : Відобразити форму введення
  deactivate app

  alt форму щойно відкрили
    user -> app : Ввести номер рахунку отримувача
    activate app
    user -> app : Ввести суму переказу
  else переказ скасовано / відмовлено
    opt
    user -> app : Змінити номер рахунку отримувача
    end
    opt
    user -> app : Змінити суму переказу
    end
  end

  opt Змінити валюту (за замовчуванням: грн)
  user -> app: Зміна валюти
  end

  app->BS: Запит балансу користувача
  activate BS
  BS->DB: Запит балансу користувача
  activate DB
  BS<--DB: Повернути баланс
  deactivate DB
  app<--BS: Повернути баланс
  deactivate BS
  app->app: Перевірити достатність коштів

  alt недостатньо коштів
  user <- app : Повідомити про відмову переказу
  else достатньо коштів
  user <- app : Відобразити форму підтвердження
  deactivate app
    alt скасовано
    user -> app : Скасувати переказ
    activate app
    else підтверджено
    user -> app : Підтвердити переказ
    end
  end

end

app->BS: Надіслати запит на переказ
activate BS
user<-app: Відобразити, що переказ в процесі
BS->DB: Оновити баланс відправника
activate DB
BS<--DB: Підтвердити
deactivate DB
BS->RB: Запит на зарахування коштів
activate RB
RB->RB: *логіка на стороні отримувача*
BS<--RB: Підтвердити
deactivate RB
BS->DB: Записати переказ
activate DB
BS<--DB: Підтвердити
deactivate DB
app<--BS: Підтвердити переказ
deactivate BS
user<-app: Повідомити про успіх переказу
deactivate app


@enduml

