@startuml
title Отримання користувачем сповіщення про оновлення валюти


actor Користувач as User
participant "Застосунок" as App
participant "Банк API" as API

User -> App : 1. Поставити сповіщення
activate App
deactivate App

loop поки дані не оновляться
App -> API : 2. Запросити дані
activate App
activate API
API --> App : 3. Отримати дані
deactivate API
end

note right
        Застосунок періодично перевіряє
        актуальні дані з API.
end note

deactivate API

App -> User : 4. Надіслати сповіщення

deactivate App
@enduml
