@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecaseBorderColor #1D2A3B
skinparam usecaseBackgroundColor #ADD1B2
skinparam actorBorderColor #1D2A3B
skinparam actorBackgroundColor #ADD1B2
skinparam linetype ortho

actor Користувач as User
actor "Банк API" as BankAPI
actor Застосунок as App

(Знайти валюту) as FindCurr
(Знайти за назвою) as FindByName
(Знайти за кодом) as FindByCode
(Знайти за фільтрами) as FindByFilters
(Встановити базову валюту) as SetBaseCurr
(Переглянути курс валюти) as ViewCurrRate
(Скористуватись конвертером) as UseConverter
(Змінити валюту 1) as ChangeCurr1
(Змінити валюту 2) as ChangeCurr2
(Ввести кількість валюти) as EnterAmount
(Переглянути історію валюти) as ViewHistory
(Порівняти історію декількох валют) as CompareHistory
(Обрати формат відображення історії) as SelectHistoryFormat
(Графік) as Chart
(Табличка) as Table
(Поставити сповіщення про оновлення валюти) as SetAlert
(Отримати сповіщення про оновлення валюти) as GetAlert
(Надіслати дані) as SendData
(Надіслати сповіщення) as SendNotif
(Отримати дані) as GetData
(Перевірити наявність з'єдняння) as CheckConnection
(Обробити дані) as ProcData
(Ініціалізувати сповіщення про оновлення валюти) as InitAlert
(з АPI) as FromAPI
(з КЕШУ) as FromCache

User --> FindCurr
User --> SetBaseCurr
User --> ViewCurrRate
User --> UseConverter
User --> ViewHistory
User --> CompareHistory
User --> SelectHistoryFormat
User --> SetAlert
User --> GetAlert

BankAPI --> SendData
BankAPI --> SendNotif

App --> GetData
App --> CheckConnection
App --> ProcData
App --> InitAlert

FindCurr <|-- FindByName
FindCurr <|-- FindByCode
FindCurr <|-- FindByFilters

UseConverter <|-- ChangeCurr1
UseConverter <|-- ChangeCurr2
UseConverter <|-- EnterAmount

SelectHistoryFormat <|-- Chart
SelectHistoryFormat <|-- Table

GetData <|-- FromAPI
GetData <|-- FromCache

ViewCurrRate .> FindCurr
ViewCurrRate .> SetBaseCurr

UseConverter .> ProcData
CompareHistory .> ProcData
ViewHistory .> ProcData
GetAlert .> ProcData

ViewHistory .> SelectHistoryFormat
CompareHistory .> SelectHistoryFormat

GetAlert .> SendNotif
GetAlert .> SetAlert
GetAlert .> InitAlert

FromAPI .> SendData

ProcData .> GetData

GetData .> CheckConnection

@enduml