@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecaseBorderColor #1D2A3B
skinparam usecaseBackgroundColor #ADD1B2
skinparam actorBorderColor #1D2A3B
skinparam actorBackgroundColor #ADD1B2
skinparam linetype ortho

actor Користувач as User
actor "Банк API" as BankAPI
actor Застосунок as App

(Знайти валюту) as FindCurr
(Встановити базову валюту) as SetBaseCurr
(Переглянути курс валюти) as ViewCurrRate
(Скористуватись конвертером) as UseConverter
(Змінити валюту) as ChangeCurr
(Ввести кількість валюти) as EnterAmount
(Переглянути історію валюти) as ViewHistory
(Порівняти історію декількох валют) as CompareHistory
(Обрати формат відображення історії) as SelectHistoryFormat
(Поставити сповіщення про оновлення валюти) as SetAlert
(Отримати сповіщення про оновлення валюти) as GetAlert
(Надіслати дані) as SendData
(Надіслати сповіщення) as SendNotif
(Отримати дані) as GetData
(Перевірити наявність з'єдняння) as CheckConnection
(Обробити дані) as ProcData
(Ініціалізувати сповіщення про оновлення валюти) as InitAlert

User --> FindCurr
User --> SetBaseCurr
User --> ViewCurrRate
User --> UseConverter
User --> ViewHistory
User --> CompareHistory
User --> SelectHistoryFormat
User --> SetAlert
User --> GetAlert

BankAPI --> SendData
BankAPI --> SendNotif

App --> GetData
App --> CheckConnection
App --> ProcData
App --> InitAlert

UseConverter <|-- ChangeCurr
UseConverter <|-- EnterAmount

ViewCurrRate .> FindCurr
ViewCurrRate .> SetBaseCurr

ChangeCurr .> FindCurr
CompareHistory .> FindCurr
ViewHistory .> FindCurr

UseConverter .> ProcData
CompareHistory .> ProcData
ViewHistory .> ProcData
GetAlert .> ProcData

ViewHistory .> SelectHistoryFormat
CompareHistory .> SelectHistoryFormat

GetAlert .> SendNotif
GetAlert .> SetAlert
GetAlert .> InitAlert

ProcData .> GetData

GetData .> CheckConnection
GetData .> SendData

@enduml