@startuml
!theme plain
hide circle
hide methods

entity "Location" as loc {
*address : string
profit : decimal <<d>>
costs : decimal <<d>>
income : decimal <<d>>
staff_count : int <<d>>
is_open : bool
}

entity "Document" as doc {
*title : string
#loc_address : string
issue_date : date
expire_date : date
is_active : bool <<d>>
}

entity "Employee" as emp {
*full_name : string
age : int
shift : string
position : string
salary : int
phone : string
}

entity "Menu" as menu {
*title : string
}

entity "Item" as item {
*title : string
recipe : string <<o>>
}

entity "Sold" as sold {
#date : date
price : decimal
}


loc ||--o{ doc : "requires"
loc }|--|{ menu : "has"
loc ||--o{ emp : "has"
menu }|--|{ item : "includes"
doc }o--o{ emp : "has"
item ||--o{ sold : "was"

@enduml




