@startuml
title Процес переказу коштів

|Користувач|
start

:Обрати "Переказ коштів";

|Застосунок|
  repeat
:Відобразити форму введення;

|Користувач|
:Вказати реквізити та суму;

if ()
    :Змінити валюту;
endif

|Застосунок|

:Надіслати запит на баланс;
note right
  Передано суму переказу
end note

|Сервер банку|
:Обробити запит на баланс;
:Надіслати відповідь;

|Застосунок|
:Перевірити достатність коштів;
note right
  Передано баланс
end note

if () then (Достатньо)


    |Застосунок|
    :Відобразити форму підтвердження;

    |Користувач|


    if ()
        :Підтвердити переказ;

        |Застосунок|

        fork
  :Відобразити, що переказ в процесі;
fork again
  :Надіслати запит на переказ;
end fork

    |Сервер банку|
    :Обробити запит на переказ коштів;
    note right
      Передано реквізити і суму
    end note
    :Надіслати відповідь;

        |Застосунок|
    :Отримати відповідь від сервера;

        if () then (Переказ підтверджено)
        :Повідомити користувача про успіх переказу;
        stop
    else (Переказ відхилено)
        :Повідомити користувача про невдачу переказу;
    endif

    else ()
            |Користувач|
        :Відхилити переказ;
    endif

else (Недостатньо)
    |Застосунок|
    :Повідомити про відмову переказу;
endif

  repeat while ()

@enduml